services:
  server:
    build: .
    container_name: front_server
    ports:
      - "5000:5000"
    volumes:
      - .:/front
    networks:
      - fitadmin_network
    restart: unless-stopped

networks:
  fitadmin_network:
    external: true
